iptomar/Transmedia

index.php, transmedia.sql
=> Create user table in database

createStory.php, index.php, transmedia.sql
=> Create table story

transmedia.sql
=> Create table video

createStory.php
=> update the form

transmedia.sql
adding and/or verifying auto_increment Primary keys on both tables
=> Auto increment of tables video and story

NavBar.php, login.php, logout.php, register.php, style/navbar.css
=> User logout

NavBar.php, addVideoToStory.php, createStory.php, my_stories.php, style/my_stories.css, transmedia.sql, verify_login.php
=> My Stories Page

storiesCatalogue.php
=> Fix bug by displaying story name instead of ID on the all stories page

NavBar.php
=> Hide 'Create Story', 'My Stories', and 'Add Video' from the navbar for unauthenticated users

transmedia.sql
=> Add image table to the database

selectedStoryPage.php, style/selected_story_page.css
Only one the current playing player appears on the page.
=> It's now possible to change between players

selectedStoryPage.php
=> Hide/show media button based on it's availability at the elapsed time

selectedStoryPage.php
=> Stop media looping in the selected story page

selectedStoryPage.php
=> Add text to selected story page

NavBar.php
=> Add Stories Catalogue page to the navbar

createStory.php
=> Improve appearance of Create Story page

my_stories.php, selectedStoryPage.php, user_profile.php
=> Create user profile page

selectedStoryPage.php
=> Fix bug preventing media display in stories without videos

about.php
=> Revise the About page and add group members information

addTextToStory.php, edit_story.php, edit_text.php, edit_text_duration.php
=> Edit texts in the edit story page

selectedStoryPage.php, style/selected_story_page.css
=> Refactor selected story page
